name: lint

on:
  push:
    branches: [master]
  pull_request:

jobs:
  pyflakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Instala pyflakes
        run: pip install pyflakes
      - name: Verifica o código
        run: pyflakes src
